version: '3'

services:
  master:
    image: locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/locust
    command: -f /locust/locustfile.py --master -H https://automationexercise.com

  worker:
    image: locust
    volumes:
      - ./:/mnt/locust
    command: -f /locust/locustfile.py --worker --master-host master
